application: sittingdbase
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: images/\1
  upload: images/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /resources/(.+)
  static_files: resources/\1
  upload: resources/(.+)  
  
- url: /.*
  script: main.application

  
libraries:
- name: webapp2
  version: latest
